export const CLIENTS_FETCHING = 'CLIENTS_FETCHING';
export const SET_CLIENTS = 'SET_CLIENTS';
export const CHANGE_CLIENT = 'CHANGE_CLIENT';
export const SET_LOADING = 'SET_LOADING'
export const SELECT_CLIENT = 'SELECT_CLIENT';
export const SET_UPDATE_LOADING = 'SET_UPDATE_LOADING';
export const SET_UPDATE_STATUS = 'SET_UPDATE_STATUS';
export const ERROR = 'ERROR';
